### ISSUE TITLE
SVG library

### ISSUE THREAD

**Issue by FAMILIAR-project** [HommeOursPorc/TuxArt#4]
an example 

`def modifCouleurPaupiereGauche(couleur):`

`def modify_left_paupiere(hexacolor, opacity=None):`

 - [ ] hexa colour 
 - [x] opacity 
 - [x] french to english 
 - [x] XML library

**Comment by FAMILIAR-project** [comment]
I don't know the Github username of Zacharie, but he should handle the adding of "hat" and various accessories... How the code integrates to @Pouteau1's one should be verified ASAP

**Comment by ark-sys** [comment]
Yep, we've noticed that he isn't in our group yet. We will add him and assign his tasks shortly
