### ISSUE TITLE
size of the tux?

### ISSUE THREAD

**Issue by acherm** [HommeOursPorc/TuxArt#9]
I'm wondering whether we can reduce the size of the tux (or adapt its width/height), typically depending on the number of options with 'y' values... 

a demonstration could show big tux, very small tux (through `make tinyconfig` instead of randconfig), or "normal" tux

**Comment by ark-sys** [comment]
Info about scaling svg : https://css-tricks.com/scale-svg/

**Comment by ark-sys** [comment]
An ideal resizing method could be - > resizetux(tux_mod, ratio) 
@parameters:
 tux_mod: tux svg file with modified colors 
 ratio: with ratio, 0=>ratio=>100 where with ratio=50 normal tux will be produce, if ratio<50, tux will be skinnier and if ratio>50, tux will be fatter
@output : tux_mod.svg

So ratio can also be used to give a specific resizing value. 

A skinnier tux should have reduced width. An even more skinnier tux should should have reduced height and width. Same thing for the fatter tux but opposite operation.

**Comment by Pouteau1** [comment]
I made a function, now we have to implement it in the main and try it out
